import {
  ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_CONCURRENT_COORDINATION_EVIDENCE_EXECUTION_DECISION_PREPARATION,
} from "./engineeringAIWorkforcePostLevelTwoConcurrentCoordinationEvidenceExecutionDecisionPreparation";

import {
  ENGINEERING_AI_WORKFORCE_CONCURRENT_COORDINATION_EVIDENCE_OWNER_APPROVAL_REASONS,
  createEngineeringAIWorkforcePostLevelTwoConcurrentCoordinationEvidenceExecutionDecision,
} from "./engineeringAIWorkforcePostLevelTwoConcurrentCoordinationEvidenceExecutionDecision";

export const ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_CONCURRENT_COORDINATION_EVIDENCE_EXECUTION_DECISION_APPROVAL_RECORD_VERSION =
  "nexus-engineering-ai-workforce-post-level-two-concurrent-coordination-evidence-execution-decision-approval-record-v1" as const;

export const ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_CONCURRENT_COORDINATION_EVIDENCE_EXECUTION_DECISION =
  createEngineeringAIWorkforcePostLevelTwoConcurrentCoordinationEvidenceExecutionDecision({
    decisionId:
      "engineering-ai-workforce-post-level-two-concurrent-coordination-evidence-execution-decision-001",

    sourcePreparation:
      ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_CONCURRENT_COORDINATION_EVIDENCE_EXECUTION_DECISION_PREPARATION,

    ownerId:
      ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_CONCURRENT_COORDINATION_EVIDENCE_EXECUTION_DECISION_PREPARATION.ownerId,

    decisions: [
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_ENGINEERING_CONCURRENT_COORDINATION_SAFETY_EVIDENCE_EXECUTION",
    ],

    reasons:
      ENGINEERING_AI_WORKFORCE_CONCURRENT_COORDINATION_EVIDENCE_OWNER_APPROVAL_REASONS,

    decidedAt:
      "2026-08-02T15:20:00.000Z",
  });