import {
  ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_EXECUTION_DECISION_PREPARATION,
} from "./engineeringAIWorkforcePostLevelTwoRepositoryReadOnlySandboxEvaluationEvidenceExecutionDecisionPreparation";

import {
  ENGINEERING_AI_WORKFORCE_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_OWNER_APPROVAL_REASONS,
  createEngineeringAIWorkforcePostLevelTwoRepositoryReadOnlySandboxEvaluationEvidenceExecutionDecision,
} from "./engineeringAIWorkforcePostLevelTwoRepositoryReadOnlySandboxEvaluationEvidenceExecutionDecision";

export const ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_EXECUTION_DECISION =
  createEngineeringAIWorkforcePostLevelTwoRepositoryReadOnlySandboxEvaluationEvidenceExecutionDecision({
    decisionId:
      "engineering-ai-workforce-post-level-two-repository-read-only-sandbox-evaluation-evidence-execution-decision-001",
    sourcePreparation:
      ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_EXECUTION_DECISION_PREPARATION,
    ownerId:
      ENGINEERING_AI_WORKFORCE_POST_LEVEL_TWO_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_EXECUTION_DECISION_PREPARATION.ownerId,
    decisions: [
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
      "APPROVE_REPOSITORY_READ_ONLY_SANDBOX_SAFETY_EVIDENCE_EXECUTION",
    ],
    reasons:
      ENGINEERING_AI_WORKFORCE_REPOSITORY_READ_ONLY_SANDBOX_EVALUATION_EVIDENCE_OWNER_APPROVAL_REASONS,
    decidedAt: "2026-08-02T19:00:00.000Z",
  });