import {
  readFileSync,
} from "node:fs";
import {
  join,
} from "node:path";
import {
  describe,
  expect,
  it,
} from "vitest";

describe("root metadata brand identity", () => {
  const source = readFileSync(
    join(
      process.cwd(),
      "app",
      "layout.tsx",
    ),
    "utf8",
  );

  it("uses the verified NEXUS product identity", () => {
    expect(source).toContain(
      'title: "NEXUS | AI Business Operating System"',
    );
    expect(source).toContain(
      'description: "Owner-controlled AI Business Operating System built for safe, clear, and accountable business operations."',
    );
  });

  it("removes the default Next.js starter metadata", () => {
    expect(source).not.toContain(
      'title: "Create Next App"',
    );
    expect(source).not.toContain(
      'description: "Generated by create next app"',
    );
  });

  it("preserves the existing root hydration boundary", () => {
    expect(source).toContain(
      'lang="en"',
    );
    expect(source).toContain(
      "suppressHydrationWarning",
    );
    expect(source).toContain(
      'className="min-h-full flex flex-col"',
    );
  });
});